### ISSUE TITLE
An undefined error was encountered during installation

### ISSUE THREAD

**Issue by zhixuzhichang** [NiuTrans/NiuTensor#1]
When I installed the GPU version, I encountered an undefined error. The error is as follows. How to fix it? Thank you very much.

`./source/tensor/core/movement/CopyValues.cuo：在函数‘nts::_CudaCopyValues(nts::XTensor const*, nts::XTensor*, nts::XStream*)’中：
tmpxft_00009cd9_00000000-5_CopyValues.compute_70.cudafe1.cpp:(.text+0x301)：对‘nts::XMemCopyAsync(void*, int, void const*, int, unsigned long, CUstream_st*, int)’未定义的引用
tmpxft_00009cd9_00000000-5_CopyValues.compute_70.cudafe1.cpp:(.text+0x541)：对‘nts::XMemCopyAsync(void*, int, void const*, int, unsigned long, CUstream_st*, int)’未定义的引用`

**Comment by xiaotong** [comment]
fixed
