### ISSUE TITLE
VS2015编译问题

### ISSUE THREAD

**Issue by zhaoxf4** [NiuTrans/NiuTensor#2]
在win10上用vs2015配置好环境，build时会出现如下output:
>1> Sum.obj : error LNK2019: 无法解析的外部符号 cblas_saxpy，该符号在函数 "void __cdecl nts::_Sum(struct nts::XTensor const *,struct nts::XTensor const *,struct nts::XTensor *,float)" (?_Sum@nts@@YAXPEBUXTensor@1@0PEAU21@M@Z) 中被引用
>1> XTensorBLAS.obj : error LNK2019: 无法解析的外部符号 cblas_sgemm，该符号在函数 "void __cdecl nts::_MatrixMULCPU(struct nts::XTensor const *,enum nts::MATRIX_TRANS_TYPE,struct nts::XTensor const *,enum nts::MATRIX_TRANS_TYPE,struct nts::XTensor *,float,float)" (?_MatrixMULCPU@nts@@YAXPEBUXTensor@1@W4MATRIX_TRANS_TYPE@1@01PEAU21@MM@Z) 中被引用
> 1>C:\Users\ZXF\Documents\Visual Studio 2015\Projects\Niutest\x64\Debug\Niutest.exe : fatal error LNK1120: 2 个无法解析的外部命令
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

如果在 **C/C++->预处理器->预处理器定义** 中去掉**USE_BLAS**则可以成功build，请问这种情况是缺少了什么库么？

**Comment by liyinqiao2012** [comment]
目前我们的NiuTensor框架支持多种CPU加速的库，其中包括MKL和OpenBlas。
加速库是否使用是通过宏定义USE_BLAS来控制的，您遇到的问题是因为您本地环境中并未安装（或并未配置好）这两个加速库，您在编译的时候发生链接错误。
您去掉USE_BLAS的库后，项目将不再使用CPU加速库，因此您可以正常编译。
倘若您希望在本地运行时获得更高的执行效率，那么这里推荐您安装MKL或者OpenBlas的库，然后即可通过添加USE_BLAS以及MKL（或OPENBLAS）的宏定义来编译，从而提升NiuTensor的速度。
