### ISSUE TITLE
有两个问题请教

### ISSUE THREAD

**Issue by dlkht** [NiuTrans/NiuTensor#5]
你好！有两个问题请教下：
1.你们提到的深度优化版本什么时候出来？
2.transformer模型训练或预测应该存在问题，什么时候改一个正确的版本我们测试一下？

**Comment by liyinqiao2012** [comment]
感谢关注，这两个部分，我们都会在月底进行更新。

**Comment by huchinlp** [comment]
谢谢关注，目前的transformer模型代码还在内部测试

**Comment by dlkht** [comment]
> 感谢关注，这两个部分，我们都会在月底进行更新。

您好！更新版本是否要发行了？

**Comment by liyinqiao2012** [comment]
> > 感谢关注，这两个部分，我们都会在月底进行更新。
> 
> 您好！更新版本是否要发行了？

方便的话留一个邮箱吧，我们把目前可用的版本提供给您，正式版还有一些文档相关的资料需要优化。

**Comment by dlkht** [comment]
> > > 感谢关注，这两个部分，我们都会在月底进行更新。
> > 
> > 
> > 您好！更新版本是否要发行了？
> 
> 方便的话留一个邮箱吧，我们把目前可用的版本提供给您，正式版还有一些文档相关的资料需要优化。

好的，我的邮箱是
qzyqzy123@21cn.com
谢谢！

**Comment by huchinlp** [comment]
邮件已回复

**Comment by dlkht** [comment]
> 邮件已回复

收到，谢谢！
打开USE_OPENBLAS选项编译没通过，是还没完善吗？

**Comment by dlkht** [comment]
> 邮件已回复

收到，谢谢！

**Comment by huchinlp** [comment]
您好！

谢谢您的反馈！
我们检查了编译示例，编译只能选择MKL、OpenBLAS和CUDA中的一项。
这是我们的失误，抱歉耽误了您的时间！
我们更新了编译示例并添加了相关说明。

再次感谢您对本项目的关注！

dlkht <notifications@github.com> 于2020年8月6日周四 下午6:24写道：

**Comment by dlkht** [comment]
好的！谢谢！
另外，我按照demo的格式训练了一个中英句对文件，设nstepcheckpoint=50000，得到一个模型数据，
但对模型执行预测命令发现结果不对。



> 您好！ 谢谢您的反馈！ 我们检查了编译示例，编译只能选择MKL、OpenBLAS和CUDA中的一项。 这是我们的失误，抱歉耽误了您的时间！ 我们更新了编译示例并添加了相关说明。 再次感谢您对本项目的关注！ dlkht <notifications@github.com> 于2020年8月6日周四 下午6:24写道：
> […](#)

**Comment by huchinlp** [comment]
感谢反馈！
我们正在修复训练和解码不一致的问题。
预计在1-2天内解决，完成后会发邮件告知您。

dlkht <notifications@github.com> 于2020年8月10日周一 下午6:16写道：

**Comment by dlkht** [comment]
好的，谢谢!

**Comment by dlkht** [comment]
> 感谢反馈！ 我们正在修复训练和解码不一致的问题。 预计在1-2天内解决，完成后会发邮件告知您。 dlkht <notifications@github.com> 于2020年8月10日周一 下午6:16写道：
> […](#)

您好！修复这个问题的版本出来没有

**Comment by wchuan163** [comment]
训练和解码不一致，查到问题没有

**Comment by liyinqiao2012** [comment]
> 训练和解码不一致，查到问题没有

已经找到问题，我们会尽快进行版本的更新。

**Comment by wchuan163** [comment]
期待新版本

**Comment by wchuan163** [comment]
大概什么时候可以更新好？

**Comment by liyinqiao2012** [comment]
> 大概什么时候可以更新好？

方便的话留个邮箱，我们可以把最最新的代码发给您，正式发布的话我们还要再优化一下。

**Comment by wchuan163** [comment]
wchuan@163.com
多谢

**Comment by wchuan163** [comment]
又一周过去了，大概什么时候可以更新好

**Comment by liyinqiao2012** [comment]
> 又一周过去了，大概什么时候可以更新好

正在测试，下周发布。因为这次的更新比较大，所以花了比较多时间。

**Comment by wchuan163** [comment]
谢谢

**Comment by huchinlp** [comment]
> 又一周过去了，大概什么时候可以更新好

你好，我们公开了NiuTrans.NMT项目，欢迎体验&吐槽~
https://github.com/NiuTrans/NiuTrans.NMT

**Comment by huchinlp** [comment]
> > 感谢反馈！ 我们正在修复训练和解码不一致的问题。 预计在1-2天内解决，完成后会发邮件告知您。 dlkht [notifications@github.com](mailto:notifications@github.com) 于2020年8月10日周一 下午6:16写道：
> > […](#)
> 
> 您好！修复这个问题的版本出来没有

你好，我们公开了NiuTrans.NMT项目，欢迎体验&吐槽~
https://github.com/NiuTrans/NiuTrans.NMT
