### ISSUE TITLE
最新NiuTrans.NMT问题

### ISSUE THREAD

**Issue by dlkht** [NiuTrans/NiuTensor#6]
训练问题：
时间长了，GPU消耗内存会变大，从而中断训练，尤其是valid数据较大时

翻译部分问题：
用自带de-en数据测试，还ok
用中英语料测试，发现问题：
1. beamsize=1时，有些句子翻译完整，有些只翻译前面部分
2. beamsize>1时，只翻译少量句子，多数句子输出空白

**Comment by huchinlp** [comment]
非常感谢您对本项目的关注！

训练时显存占用过高的问题我们正在排查中。

翻译使用其他数据遇到的问题可能是这几个原因造成的：
1. 我们的代码中对输入句子做了长度截断，默认是120个词，您可能需要看一下未完整翻译的句子是不是过长。
2. 词表转换问题，我们默认使用：
    PAD=1
    SOS=2
    EOS=2
    UNK=3
您可以检查一下词表转换之后的id。

如果还有问题，您可以联系huchinlp[at]gmail.com

**Comment by dlkht** [comment]
> 非常感谢您对本项目的关注！
> 
> 训练时显存占用过高的问题我们正在排查中。
> 
> 翻译使用其他数据遇到的问题可能是这几个原因造成的：
> 
> 1. 我们的代码中对输入句子做了长度截断，默认是120个词，您可能需要看一下未完整翻译的句子是不是过长。
> 2. 词表转换问题，我们默认使用：
>    PAD=1
>    SOS=2
>    EOS=2
>    UNK=3
>    您可以检查一下词表转换之后的id。
> 
> 如果还有问题，您可以联系huchinlp[at]gmai
