### ISSUE TITLE
你好 我在安装的时候总是提示缺少libdf.so.2包 请问是什么问题

### ISSUE THREAD

**Issue by binbinjiang** [NiuTrans/NiuTensor#8]

**Comment by liyinqiao2012** [comment]
您邮件中提到的是缺少libdl.so.2的库文件，这个文件是GLIBC中提供的，因此有可能是因为您设备中GLIBC版本过低的问题。您可以尝试安装更新版本的GLIBC之后再次进行编译。我们之前测试的环境中GLIBC版本是2.17，可正常编译NiuTensor，供您参考。

**Comment by binbinjiang** [comment]
你好 已解决，原因是你们将CMmakelis.txt中的libdl.so.2的路径写死（/usr/lib64/libdl.so.2）,但是我发现很多服务器该文件地址并非如此，所以建议后续可以改进下！十分感谢!

**Comment by liyinqiao2012** [comment]
ok，抱歉给您带来的困扰，这个问题我们会在下个版本中进行修复，希望您继续对NiuTensor以及NiuTrans团队的其他相关开源项目进行关注。
