### ISSUE TITLE
基于CPU的FP16有支持计划么

### ISSUE THREAD

**Issue by bcmi220** [NiuTrans/NiuTensor#9]
您好，

在NiuTensor的Roadmap中看有支持CPU FP16的计划，请问有预计的支持/开放时间么（当前OpenBLAS好像已经支持了BFLOAT16）？看最近Tencent的NCNN和Alibaba的MNN推理框架都已经支持了FP16。

**Comment by liyinqiao2012** [comment]
感谢您的关注，对于CPU FP16的部分我们有这个计划，也正在顺利推进中，有进展我们会在官网以及GitHub平台进行及时更新，欢迎继续关注。
